### PR TITLE
Add NavBar

### PR DESCRIPTION
**Pull request by ajayns**

### CODE REVIEW

**Comment by datakurre** [comment]
@ajayns Because I added this into travis-ci.org, you probably need to disable Travis-build from travis-ci.com https://github.com/collective/gatsby-starter-plone/settings/installations

For some reason the gh-pages token is not available at travis-ci.com. I don't know why.

**Comment by ajayns** [comment]
Oh yes will handle that! @datakurre

**Comment by ajayns** [comment]
Also, should I delete Travis CI from Services in https://github.com/collective/gatsby-starter-plone/settings/installations

**Comment by datakurre** [comment]
@ajayns You can try. If it breaks after that we can re-enable it from Travis-CI.org

**Pull request merged**
